import 'highlight.js/styles/agate.css'

import Head from 'next/head'

import { GetBlogListQuery } from '@/graphql'

import client from './apollo'
import { GET_BLOG_LIST } from './gql'
import { markdown } from './utils/markdown'
interface HomeProps {
  blog: GetBlogListQuery['blog']
}
export default function Home({ blog }: HomeProps) {
  return (
    <div className={''}>
      <Head>
        <title>ABFree</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/apps/blog/public/favicon.ico" />
      </Head>
      <div className={'prose prose-stone mx-auto '}>
        {blog.length > 0 && (
          <div
            dangerouslySetInnerHTML={{
              __html: markdown.render(blog[0].content!),
            }}
          ></div>
        )}
      </div>
    </div>
  )
}
export const getStaticProps = async () => {
  const { blog } = (
    await client.query<GetBlogListQuery>({
      query: GET_BLOG_LIST,
    })
  ).data
  return {
    props: {
      blog,
    },
  }
}
